### ISSUE TITLE
component property names ('s capitalization)

### ISSUE THREAD

**Issue by grandchild** [azeem/webvs#15]
hey there, azeem and others,
i am now starting to adapt the output of the avs file converter to the actual property names used in the code of webvs.
major question: how open are you guys to discussions about changing this or that name for a component's property? there are two sides to consider:
- converter: the changes are pretty easy, i just change the name of the property in my component list, done.
- webvs: usage of property names might be a bit more stretched out, but as far as i can see it's mostly inside the class/file defining the component and in the example presets.
  i don't think property names are something worth starting a fight over, but i might like to suggest something more appropriate from time to time.

such as property capitalization: is the reading/comparison of any names from the json files case-insensitive? i'd like it to be this way, because case is basically irrelevant and a matter of taste (e.g. i like CamelCase) and the values of enum-like properties are ALLCAPS in the webvs code and examples. i'd like it to just not matter what case the values of json strings have.
thoughts?

**Comment by azeem** [comment]
Is this issue relevant anymore? Can we close this?

**Comment by grandchild** [comment]
Well unless we want to reconsider case-insensitivity (right now enums have to be allcaps, if i'm not mistaken), webvs and webvsc have been aligned by #40, and this can be closed.
