### ISSUE TITLE
None of the examples work, because the music has been removed from Soundcloud. 

### ISSUE THREAD

**Issue by Kakurady** [azeem/webvs#29]
All the examples tries to load this track: [https://soundcloud.com/gigamesh/fleetwood-mac-dreams-gigamesh]()

But it seems to be gone.

I was hoping to see some Llama Tail-whipping Action.

**Comment by Kakurady** [comment]
Trying to load something does exist gives a message about cross-origin restrictions.

**Comment by azeem** [comment]
I have a new example with local audio files. Are you checking the latest master branch?

**Comment by Kakurady** [comment]
Right, but [the website](http://azeemarshad.in/webvs/#examples) is still using old examples.

**Comment by azeem** [comment]
Ah i see. Thanks for pointing that out. I'm working on some updated docs, will upload the examples on the website.
